---
title: "ST2195 Programming for Data Science"
author: "Lee Hin Sing Raymond"
date: "December 2021"
output: pdf_document
---

# Practice Assignment 2

### Introduction

This is the second assignment for the course [**ST2195 Programming for Data Science**](https://www.lse.ac.uk/study-at-lse/uolip/Assets/documents/21-22-CIS-Sheets/ST2195-Programming-for-data-science.pdf). R and Python programming will be the main focus of this introductory course.

This is a compulsory 200-course for students who are going for a **BSc Data Science and Business Analytics** degree in the University of London, the academic direction of the degree program is provided by [London School of Economics and Political Science](https://www.lse.ac.uk/) (LSE). The course convenors are Mr [Ioannis Kosmidis](https://www.ikosmidis.com/) and Dr [Kostas Kalogeropoulos](https://www.lse.ac.uk/Statistics/People/Dr-Kostas-Kalogeropoulos).

Throughout the half-year course, there will be a take-home assignment every two weeks to demonstrate what we have learned before. All final works should be uploaded to a GitHub repository for version control.

### Assignment

Create a GitHub repository called “st2195_assignment_2” that includes:

* a README.md file with a short markdown description of this assignment [1 point]

* a folder called “r_csv” with a R code for scraping the CSV example on cars in the Wikipedia page https://en.wikipedia.org/wiki/Comma-separated_values and saving the resulting output in the local folder (in CSV) [4.5 points – module E]

* a folder called “python_csv” with a Python version of the code in point 2 [4.5 points – module F]

Note that it is advised to use the packages rvest (R) and BeautifulSoup (Python) for scaping operations. RSelenium (R) and Selenium (Python) can also be used, but they are generally more complicated to setup.

Hint: You may want to have a look of https://rvest.tidyverse.org/articles/harvesting-the-web.htm